# Outputs
Output endoflife.date.maven.mp4
Output endoflife.date.maven.webm
Output endoflife.date.maven.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 20
Set Width 1200
Set Height 600

# Type a command in the terminal.
Type "# 🎄 Are you aware Apache Maven 🪶  EoLs have just landed on endoflife.date ❔"
Enter

# Pause for dramatic effect...
Sleep 500ms


Type "# 💡 Let's take a look at it with eol cli"
Enter
Type "eol maven"
Enter
Sleep 5s


Type "# 🪄 You can also call get it from your favorite alias"
Enter
Type "eol mvn"
Enter
Sleep 5s



Type "# 🔖 Feel free to visit https://endoflife.date/maven for more"
Enter
Sleep 3s


Sleep 1s
Type "# 🤓 Take a look at issues waiting for contributors for [Request - Product]..."
Sleep 2s
Enter
Type "# ... and of course spread Maven around the 🌏"
Sleep 4s