# Outputs
Output endoflife.date.mp4
Output endoflife.date.webm

# Set up a 1200x600 terminal with 46px font.
Set FontSize 20
Set Width 1200
Set Height 600

# Type a command in the terminal.
Type "# 🙋  So you want to know more about EOL and apps/frameworks lifecycle ❔"
Enter

# Pause for dramatic effect...
Sleep 500ms


Type "# 💡 First, more about eol cli"
Enter
Type "clear"
Enter
Type "eol --help"
Enter
Sleep 5s
Type clear
Enter

Type "# 👉  Then go and play with eol and endoflife.date 👇"
Enter
Sleep 500ms

Type "clear"
Enter
Type "# 🍃 Enjoy Spring-Boot EOLs"
Enter
Sleep 500ms
Type "eol spring-boot"
Enter
# Admire the output for a bit.
Sleep 5s

Type "clear"
Enter
Type "# 🚀  Or Quarkus one"
Enter
Type "eol quarkus | more"
Enter
# Admire the output for a bit.
Sleep 5s
Type "q"

Type "clear"
Enter
Type "# ☕ Get java EOL"
Enter
Type "eol java"
Enter
# Admire the output for a bit.
Sleep 5s


Sleep 500ms
Type "clear"
Enter
Type "# 📑  Or any other EOL of the (ever growing) list"
Enter
Sleep 500ms
Type "eol | less"
Enter
Down
Down
Sleep 600ms
Down
Down
Sleep 600ms
Down
Down
Sleep 600ms
Down
Down
Sleep 600ms
Down
Down
Sleep 600ms
Down
Down
Sleep 600ms
Down
Down
Sleep 600ms
Down
Down
Type "q"
Enter
# Admire the output for a bit.
Sleep 1s
Type "# 🔖 Go to https://endoflife.date/ for more."
Sleep 5s
